name: flutter_test_2
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
    sdk: ">=2.3.0 <3.0.0"
dependencies:
    flutter:
        sdk: flutter
    intl: ^0.16.1
    cupertino_icons: ^0.1.3
    provider_architecture: ^1.0.3
    responsive_builder: ^0.1.4
    provider: ^3.2.0
    logger: ^0.7.0+2
    get_it: ^3.0.3
    equatable: ^1.0.1
dev_dependencies:
    flutter_test:
        sdk: flutter
flutter:
    uses-material-design: true
    fonts:
        - family: Roboto
          fonts:
              - asset: assets/fonts/Roboto-Regular.ttf
              - asset: assets/fonts/Roboto-Italic.ttf
              - asset: assets/fonts/Roboto-BlackItalic.ttf
              - asset: assets/fonts/Roboto-Light.ttf
              - asset: assets/fonts/Roboto-Thin.ttf
                weight: 700
        - family: Synemono
          fonts:
              - asset: assets/fonts/SyneMono-Regular.ttf
    # To add assets to your application, add an assets section, like this:
    assets:
     - assets/images/waiting.png
     - assets/images/eror404.jpg
     # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.
    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages
    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
